language: cpp

sudo: required
dist: trusty

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update;
    brew install qt5;
    brew install gcc;
    brew link --overwrite gcc;
    brew install g-node/homebrew-data/nixio;
    fi

  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-get install -q gcc-4.8 g++-4.8 libstdc++-4.8-dev libboost-all-dev -y;
    sudo apt-get install libcppunit-dev libboost-all-dev libhdf5-serial-dev libhdf5-dev libhdf5-7 -y;
        
    sudo apt-add-repository ppa:beineri/opt-qt562-trusty -y;
    sudo apt-get update;
    sudo apt-get install qt56-meta-minimal qt56x11extras -y;
    
    sudo add-apt-repository ppa:gnode/nix -y;
    sudo apt-get update;
    sudo apt-get install libnix-dev -y;
    g++ --version;
    fi

  
install:
  - if [ "$CXX" == "g++" ]; then 
    export CXX="g++-4.8"; 
    export COMPILER="g++";
    $CXX --version; 
    else 
    clang --version;
    fi

script: 
  - if [  "$TRAVIS_OS_NAME" == "linux" ]; then
    /opt/qt56/bin/qt56-env.sh;
    export CMAKE_PREFIX_PATH=/opt/qt56;
    cmake . && make;
    fi
  
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    export CMAKE_PREFIX_PATH=/usr/local/opt/qt5;
    cmake . && make;
    fi
